### ISSUE TITLE
Make perf major version change

### ISSUE THREAD

**Issue by mattcat10** [xotahal/fastlane-plugin-semantic_release#21]
Make "perf" type major change - the same as semantic release
https://github.com/semantic-release/semantic-release

<img width="876" alt="Screen Shot 2020-05-04 at 2 36 08 PM" src="https://user-images.githubusercontent.com/5581187/81006182-b11a4380-8e14-11ea-804e-5123dd44e2a2.png">

**Comment by xotahal** [comment]
Hey mate, they don't do Major version because of `perf`. They do major version because of BREAKING CHANGE down in the comment.

There is nothing about major version for perf in this (that's what we follow) - https://www.conventionalcommits.org/en/v1.0.0/


Anyway, if you like to override this behaviour, you can use this parameter ...
```
          FastlaneCore::ConfigItem.new(
            key: :releases,
            description: "Map types of commit to release (major, minor, patch)",
            default_value: { fix: "patch", feat: "minor" },
            type: Hash
          ),
```
